version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.8.3
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.1
  - dependency-name: netlify-lambda
    versions:
    - 2.0.2
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
