[build]
    functions = "functions"
    publish = "public"
    command = "npm run build"

[[headers]]
    for = "/*"
    [headers.values]
        Expect-CT = "max-age=0, report-uri='https://panda.report-uri.com/r/d/ct/reportOnly'"
        Referrer-Policy = "strict-origin-when-cross-origin"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"

# ------------------------------------------------------------------------------
# Redirects
# ------------------------------------------------------------------------------

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api"
    status = 200
    force = false

[[redirects]]
    from = "/postcode/*"
    to = "https://api.postcodes.io/postcodes/:splat"
    status = 200
    force = false

[[redirects]]
    from = "/1.0.13--beta/*"
    to = "https://v1-0-14--carbon-gizmo.netlify.com/:splat"
    status = 200
    force = false

[[redirects]]
    from = "/1.0.14--beta/*"
    to = "https://v1-0-14--carbon-gizmo.netlify.com/:splat"
    status = 200
    force = false

[[redirects]]
    from = "/2.0.0/*"
    to = "/:splat"
    status = 200
    force = false
